development:
    adapter: postgresql
    database: billshare
    pool: 5
    username: postgres
    password: 
    
test:
    adapter: postgresql
    database: billshare
    pool: 5
    username: postgres
    password: